server:
  port: 8080
  forward-headers-strategy: framework

spring:
  profiles:
    active: dev
  datasource:
    url: 'jdbc:h2:mem:${DB_URL}'
    driver-class-name: org.h2.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect

    show_sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  security:
    user:
      password: 1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**

cloud:
    aws:
      s3:
        bucket: cow-insta-practice
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2
        auto: false
      stack:
        auto: false
