name: CI

on:
  push:
    branches: [ main ]

#env:
#  S3_BUCKET_NAME: cow-insta-practice
#  RESOURCE_PATH: ./src/main/resources/application.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

#      - name: Set YML
#        uses: microsoft/variable-substitution@v1
#        with:
#          files: ${{ env.RESOURCE_PATH }}
#        env:
#          spring.datasource.username: ${{ secrets.DB_USERNAME }}
#          spring.datasource.password: ${{ secrets.DB_PASSWORD }}
#          AWS.ACCESS.KEY.ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS.SECRET.KEY: ${{ secrets.AWS_SECRET_KEY }}

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Test with Gradle
        run: ./gradlew build jacocoTestReport
