name: CI

on:
  push:
    branches: [ main ]

env:
  S3_BUCKET_NAME: cow-insta-practice
  RESOURCE_PATH: ./src/main/resources/application.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - run: touch ./src/main/resources/application-secrets.properties
      - run: echo "${{ secrets.APPLICATION_SECRET }}" > ./src/main/resources/application-secret.properties
      - run: cat ./src/main/resources/application-secret.properties

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Test with Gradle
        run: ./gradlew build jacocoTestReport

      - name: Make Directory
        run: mkdir cicd

      - name: Copy Jar
        run: cp ./build/libs/*.jar ./cicd

      - name: Copy appspec.yml
        run: cp appspec.yml ./cicd

      - name: Copy script
        run: cp deploy.sh ./cicd

      - name: Make zip file
        run: zip -r ./insta.zip ./cicd
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./insta.zip s3://$S3_BUCKET_NAME/

      - name: Deploy
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          aws deploy create-deployment \
          --application-name cow_insta \
          --deployment-group-name cow_insta-group \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=cow-insta-practice,bundleType=zip,key=insta.zip \
          --region ap-northeast-2
#        |
#          aws deploy create-deployment
#          --application-name [cow_insta]
#          --deployment-group-name [cow_insta-group]
#          --file-exists-behavior OVERWRITE
#          --s3-location bucket=cow-insta-practice, bundleType=zip, key=insta.zip
#          --region ap-northeast-2
